# code used to convert a tree generated by clustering methods into parenthetic format

library(ape)
library(dendextend)
library(cluster)
library(tibble)
library(magrittr)
library(dplyr)

# function converting generical clustering object into dendrogram object
to.dend = function(cl.obj){
  cluster.obj = cl.obj %>% as.hclust()
  dend = cluster.obj %>% as.dendrogram(hang = -1, check = TRUE)
  return(dend)
}

# formating the obtained dendrogram into parentical format
convert_to_par <- function(dend, first_it =  TRUE)
{
  if (first_it == TRUE){
    dist = as.double(attr(dend, "height"))
    dend.object1 = dend[[1]]
    dist1 = as.double(attr(dend.object1, "height"))
    dend.object2 = dend[[2]]
    dist2 = as.double(attr(dend.object2, "height"))
    first_it = FALSE
    return(paste0("((",
                  convert_to_par(dend.object1, first_it),
                  "):",
                  dist - dist1,
                  ",",
                  "(",
                  convert_to_par(dend.object2, first_it),
                  "):",
                  dist - dist2,
                  ");"))
  }else{
      dist = as.double(attr(dend, "height"))
      dend.object1 =  dend[[1]]
      dist1 = as.double(attr(dend.object1, "height"))
      dend.object2 = dend[[2]]
      dist2 = as.double(attr(dend.object2, "height"))
      if(is.list(dend.object1) == TRUE & is.list(dend.object2) == TRUE){
      return(paste0("(",
                    convert_to_par(dend.object1, first_it),
                    "):", dist - dist1,
                    ",",
                    "(",
                    convert_to_par(dend.object2, first_it),
                    "):", dist - dist2))
      }else{
        if(is.list(dend.object1) == FALSE & is.list(dend.object2) == TRUE){
          label1 = attr(dend.object1,"label")
          return(paste0(label1, ":",
                        dist - dist1,
                        ",",
                        "(",
                        convert_to_par(dend.object2, first_it),
                        "):", dist - dist2))
        }else{
          if(is.list(dend.object1) == TRUE & is.list(dend.object2) == FALSE){
            label2 = attr(dend.object2, "label")
            return(paste0("(",
                          convert_to_par(dend.object1, first_it),
                          "):", dist - dist1, ",",
                          label2, ":",
                          dist - dist2))
          }else{
            label1 = attr(dend.object1, "label")
            label2 = attr(dend.object2, "label")
            return(paste0(label1, ":", dist - dist1,
                          ",",
                          label2, ":", dist - dist2))
          }
        }
      }
    }
}

# test using DIANA clustering method on USAarrests data

data("USArrests")
arrests_df = USArrests %>%
  as_tibble()
arrests_df
arr.diana = arrests_df %>%
  diana()
dend.diana = to.dend(arr.diana)
parenthetic_test = convert_to_par(dend.diana, first_it = TRUE)
parenthetic_test

# comparing the parenthetic and dendrogram format by plotting
tree.obj = read.tree(text = parenthetic_test)
plot(tree.obj, no.margin = TRUE, edge.width = 2)
plot(dend.diana)

